# Generated by Django 3.2.20 on 2023-10-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_assessmentworkflowstep_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentworkflow',
            name='student_id',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
