# Generated by Django 3.2.20 on 2023-10-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_assessmentworkflow_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentworkflow',
            name='student_id',
            field=models.CharField(db_index=True, default='uuuuv', max_length=255),
        ),
    ]
