# Generated by Django 3.2.20 on 2023-10-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_alter_assessmentworkflow_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentworkflow',
            name='student_id',
            field=models.CharField(default='uuuuv', max_length=255),
        ),
    ]
