# Generated by Django 3.2.20 on 2023-10-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_alter_historicalsharedfileupload_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsharedfileupload',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical shared file upload'},
        ),
    ]
