# Generated by Django 3.2.20 on 2023-10-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_alter_historicalsharedfileupload_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsharedfileupload',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical shared file upload', 'verbose_name_plural': 'historical shared file uploads'},
        ),
    ]
